### ISSUE TITLE
/unlogin command

### ISSUE THREAD

**Issue by ItsVaidas** [kyngs/LibreLogin#173] opened 2023-11-28 15:22 UTC
Now there is sessions for login.
We have a case where a player joins into the server from his friends house, and because of the session, his friend can now join whenever he wants with his account until the account owner logins from other IP.
With /unlogin command it should cancel the session and on the next login would require to login again on next join

**Comment by kyngs** [comment] 2023-11-28 15:32
Duplicate of #117

**Closed by kyngs** 2023-11-28 15:32 UTC
