### ISSUE TITLE
Add the possibility to register limbos and lobbies dynamicaly through the API

### ISSUE THREAD

**Issue by AurelienConte** [kyngs/LibreLogin#49] opened 2023-03-07 17:49 UTC
Hi,

This isssue is a reference to my use case. Building a network of servers who are dynamicaly provided, i can't write server names in the config direclty since  instances are created and shutdowned on the fly. 

I nice feature would be to be able to add servers via the API of the plugin.

**Comment by kyngs** [comment] 2023-03-07 17:55
Yeah, the entire server system needs some rewriting

**Comment by kyngs** [comment] 2023-03-07 18:51
Until then, you ***could*** use the Lobby/LimboServerChooseEvent
However, I will try to implement proper API ASAP.

**Comment by AurelienConte** [comment] 2023-03-07 19:31
Good point, it can be enought for me. 
Just one more point, if i try to push a config file with no servers configured (or bad one) i am getting an error on startup so... 

Are you open to some PR on this project ? And have you some guidelines about it ? 

If i can, i would be happy to provide this feature myself.

**Comment by kyngs** [comment] 2023-03-07 19:43
> Good point, it can be enought for me. Just one more point, if i try to push a config file with no servers configured (or bad one) i am getting an error on startup so...
> 
> Are you open to some PR on this project ? And have you some guidelines about it ?
> 
> If i can, i would be happy to provide this feature myself.

At the moment I am working on this. I will probably finish it today or tomorrow. So, in this case, I suggest you not to PR this feature.

**Comment by kyngs** [comment] 2023-03-07 20:09
Can you please build the latest commit on dev and try it out? As for your maven version, use `dev-SNAPSHOT`. Tell me whether it works correctly so I can push it to release.

**Comment by AurelienConte** [comment] 2023-03-08 05:48
I have rebuild the project from the dev branch and i have droped to my velocity proxy as the first step 
He is shutdown with : 

[05:47:39 ERROR] [librelogin]: !! THIS IS MOST LIKELY NOT AN ERROR CAUSED BY LIBRELOGIN !!
[05:47:39 ERROR] [librelogin]: !!The configuration is corrupted, please look below for further clues. If you are clueless, delete the config and a new one will be created for you. Cause: CorruptedConfigurationException: The supplied pass-through server lobby1 is not configured in the proxy configurattion!

Even if a do not specify any limbo servers and lobby servers.

**Comment by kyngs** [comment] 2023-03-08 16:05
Sorry for the late reply, I forgot to remove the check. Use the latest commit

**Comment by AurelienConte** [comment] 2023-03-08 20:46
Sorry too for the late reply, but duuuuddddeeee i just tested and that's work like a charm !

**Comment by AurelienConte** [comment] 2023-03-08 21:11
Okay, i have tried the DB connection and that's work nicely but no IP update / lastServer / lastAuthentication (I don't know if i should post it in this issue but since this is related to the dev branch.. )

**Comment by kyngs** [comment] 2023-03-09 10:01
> Okay, i have tried the DB connection and that's work nicely but no IP update / lastServer / lastAuthentication (I don't know if i should post it in this issue but since this is related to the dev branch.. )

Can you double check this does not happen on master? It kinda doesn't make sense

**Comment by AurelienConte** [comment] 2023-03-09 20:11
After some tests, it seem's the problem is more complexe. 

I have tried a connection with a cracked account and everything is working correcly.
The lastServer is also working after a proxy reboot soo ok !

But for premiums, the ip field is not filled. And the lastAuthentication field also but idk if this field should be filled since i have enabled the autoLogin feature.

My setup doesn't allow me to test the main branch easily unfortunately.

**Comment by kyngs** [comment] 2023-03-09 20:51
The IP and last authentication is only filled when the player authenticates using /login. So, I think you're probably observing intended behavior.

**Comment by AurelienConte** [comment] 2023-03-10 16:43
Okay i was thinking this will be the lastIp / Last time where player has connected (this will be more pertinent).

**Comment by kyngs** [comment] 2023-03-10 21:39
Okay, closing this as completed.

**Closed by kyngs** 2023-03-10 21:39 UTC
