### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous player kick!

### ISSUE THREAD

**Issue by RecoveryDyne** [kyngs/LibreLogin#61] opened 2023-04-09 07:54 UTC
Error pops up after somebody logging in...
```java
[10:37:20 ERROR]: Thread ForkJoinPool-2-worker-1 failed main thread check: player kick

java.lang.Throwable: null

at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-307]

at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:617) ~[paper-1.19.2.jar:git-Paper-307]

at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:612) ~[paper-1.19.2.jar:git-Paper-307]

at xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189) ~[LibreLogin.jar:?]

at xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43) ~[LibreLogin.jar:?]

at xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69) ~[LibreLogin.jar:?]

at xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45) ~[LibreLogin.jar:?]

at xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148) ~[LibreLogin.jar:?]

at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403) ~[?:?]

at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]

at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]

at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]

at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]

[10:37:20 WARN]: java.lang.IllegalStateException: Asynchronous player kick!

[10:37:20 WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)

[10:37:20 WARN]: at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:617)

[10:37:20 WARN]: at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:612)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

[10:37:20 ERROR]: [LibreLogin] An unexpected exception occurred while performing command, please attach the stacktrace below and report this issue.

[10:37:20 WARN]: java.lang.IllegalStateException: Asynchronous player kick!

[10:37:20 WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)

[10:37:20 WARN]: at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:617)

[10:37:20 WARN]: at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.kick(CraftPlayer.java:612)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:189)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.paper.PaperLibreLogin.authorize(PaperLibreLogin.java:43)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.authorization.AuthenticAuthorizationProvider.authorize(AuthenticAuthorizationProvider.java:69)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.command.commands.authorization.RegisterCommand.lambda$onRegister$0(RegisterCommand.java:45)

[10:37:20 WARN]: at LibreLogin.jar//xyz.kyngs.librelogin.common.util.GeneralUtil.lambda$runAsync$0(GeneralUtil.java:148)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)

[10:37:20 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by kyngs** [comment] 2023-04-09 09:50
Duplicate of #57

**Closed by kyngs** 2023-04-09 09:50 UTC
