### ISSUE TITLE
Add an option to disable chat prompts in the configuration file

### ISSUE THREAD

**Issue by xiamozy** [kyngs/LibreLogin#270] opened 2024-07-18 07:43 UTC
I only want to keep the login titles prompt and disable all other prompts. For example: use-action-bar=false, use-titles=true, use-chat=false.

**Comment by bivashy** [comment] 2024-07-18 12:34
I guess this is duplicate of: #135

**Comment by kyngs** [comment] 2024-07-18 19:57
It is.

**Closed by kyngs** 2024-07-18 19:57 UTC
