### ISSUE TITLE
FATAL error with protocol

### ISSUE THREAD

**Issue by YKDZ** [kyngs/LibreLogin#101] opened 2023-07-05 02:55 UTC
[10:26:35 FATAL]: A plugin tried to deny a command with signable component(s). This is not supported. Disconnecting player ***
This error will appear when using any command of LibreLogin. Then player will be kicked with this error:
![Snipaste_2023-07-05_10-26-48](https://github.com/kyngs/LibreLogin/assets/69898831/c9770a46-d8d0-4473-b0b3-eefe32be1c44)

**Comment by kyngs** [comment] 2023-07-05 07:43
1) You're using the command while not authenticated
2) This is a duplicate of #67 
3) Unfortunately, we cannot do anything about this. This is a velocity issue. (See https://github.com/PaperMC/Velocity/issues/935) You can install [UnsignedVelocity](https://modrinth.com/plugin/unsignedvelocity/version/1.4.2) and disable command signing in its config.

**Closed by kyngs** 2023-07-05 07:43 UTC
