### ISSUE TITLE
Block chat for unauthorized players

### ISSUE THREAD

**Issue by cute-sakura** [kyngs/LibreLogin#194] opened 2023-12-26 16:20 UTC
Unauthorized players can use chat while sitting at login screen, and it's visible in server log and to other online players
```[19:14:57 INFO]: <Awatest> test message```
So attacker can speak as a legit player (or even server admin!) and confuse other online players

**Comment by kyngs** [comment] 2023-12-26 16:22
That's very sussy. This definitely should not happen. Are you running on a standalone server or under a proxy (such as Velocity, or BungeeCord)?

**Comment by kyngs** [comment] 2023-12-26 16:31
Can you send the logs? Do you use any chat plugin?

**Comment by kyngs** [comment] 2023-12-26 16:40
> > Can you send the logs? Do you use any chat plugin?
> 
> can i send it privately to you? by email for example?

You can either join our discord in the readme and then send it in my private messages, or you can mail the logs at `other@kyngs.xyz`

**Comment by kyngs** [comment] 2023-12-26 17:36
> > You can either join our discord in the readme and then send it in my private messages, or you can mail the logs at `other@kyngs.xyz`
> 
> sent to email!

Probably some plugin is interfering, can you replicate the issue without any other plugins than librelogin and protocollib?
If not, try to find which plugin causes the issue to happen.

**Comment by kyngs** [comment] 2023-12-26 18:03
Thanks for sharing your findings, I'll try to replicate it locally and report back.

**Comment by kyngs** [comment] 2023-12-26 18:06
What plugin are you using? I tried this one https://www.spigotmc.org/resources/no-chat-reports.102990/ And I can not reproduce the issue.

**Comment by kyngs** [comment] 2023-12-26 18:17
Where did you download the no chat reports plugin from?

**Comment by kyngs** [comment] 2023-12-26 18:20
Honestly, I have no idea, I suggest you use a different plugin to disable chat reporting. I'm closing this issue as it is not caused by LibreLogin

**Closed by kyngs** 2023-12-26 18:20 UTC
